classes = [
    'align-items-center',
    'bg-light',
    'col',
    'd-flex',
    'hugo-mod-icon',
    'justify-content-center',
    'mb-4',
    'mt-2',
    'p-5',
    'text-center',
    'text-muted',
    'user-select-all',
]
